### ISSUE TITLE
RuntimeError in cpu mode

### ISSUE THREAD

**Issue by masud-src** [CBICA/BrainMaGe#15]
Hi, 

i was running in an runtime error, because I was running within the cpu mode. See the Traceback:

`Traceback (most recent call last):
  File "/home/marlon/anaconda3/envs/brainmage/bin/brain_mage_run", line 4, in <module>
    __import__('pkg_resources').run_script('BrainMaGe==1.0.5.dev0', 'brain_mage_run')
  File "/home/marlon/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/marlon/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1464, in run_script
    exec(code, namespace, namespace)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/BrainMaGe-1.0.5.dev0-py3.6.egg/EGG-INFO/scripts/brain_mage_run", line 213, in <module>
    test_ma.infer_ma(params_file, DEVICE, args.save_brain, weights)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/BrainMaGe-1.0.5.dev0-py3.6.egg/BrainMaGe/tester/test_ma.py", line 155, in infer_ma
    checkpoint = torch.load(str(params["weights"]))
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/marlon/anaconda3/envs/brainmage/lib/python3.6/site-packages/torch/serialization.py", line 138, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
`

I was able to hotfix this issue by changing the line 155, just like the error is saying:

`checkpoint = torch.load(str(params["weights"]),map_location=torch.device('cpu'))`

Maybe this line should also go into the if clause, that checks for the device (two lines later). Just to let you know. Everything works fine then for me. Great work!

Cheers

**Comment by sarthakpati** [comment]
Hey @masud-src,

Thank you for your interest in BrainMaGe, and reporting this! 

Would it be possible for you to put a pull request with this fix so that we can try it out?
