### ISSUE TITLE
Horovod Error

### ISSUE THREAD

**Issue by jayurbain** [CBICA/BrainMaGe#9]
`pytorch '1.9.0+cu102'`
`horovod '0.22.1'` #used: HOROVOD_WITH_PYTORCH=1 pip install horovod[pytorch]

When I run the following command:
```bash
python ../BrainMaGe/brain_mage_run.py -params test_params_multi_4_2020.cfg -test True -mode Multi-4 -dev gpu
```

I get this error. 
```python-traceback
Extension horovod.torch has not been built: /opt/conda/lib/python3.7/site-packages/horovod/torch/mpi_lib/_mpi_lib.cpython-37m-x86_64-linux-gnu.so not found
If this is not expected, reinstall Horovod with HOROVOD_WITH_PYTORCH=1 to debug the build error.
Warning! MPI libs are missing, but python applications are still avaiable.
Traceback (most recent call last):
  File "../BrainMaGe/brain_mage_run.py", line 118, in <module>
    version=pkg_resources.require("BrainMaGe")[0].version
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/conda/lib/python3.7/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (SQLAlchemy 1.4.22 (/opt/conda/lib/python3.7/site-packages), Requirement.parse('sqlalchemy<1.4.0.dev0'), {'pybids'})
```

Why is it looking for a conda environment? Do I need to explicitly create a conda environment?

Thanks,
Jay

**Comment by sarthakpati** [comment]
Hi Jay,

Thank you for your interest in BrainMaGe!

I have not tested this with horovod, so we won't be able to help you much. Unless @Geeks-Sid has any additional information?

**Comment by jayurbain** [comment]
Thanks. My actual fatal error was not having the correct SQLAlchemy installed. Correcting that allowed me to run the program. However I still get the horovod warning which I'm ignoring for now.
